
language: android
sudo: true
before_install:
  - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
  - unzip -oq android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r16b
  - export ANDROID_HOME=$PWD/sdk
  - chmod +x gradlew
  - chmod +x cdep
  - set -e
  - ./cdep
  - cat cdep.sha256
